#!/usr/bin/env node

import chalk from "chalk";
import chalkAnimation from 'chalk-animation';
import figlet from "figlet";
import gradient from "gradient-string";
import banner from 'node-banner';
import inquirer from "inquirer";
import { createSpinner } from "nanospinner";


let round: number, count:number;
round = 1,count=0;

const sleep= () => new Promise((resolve)=> setTimeout(resolve,2000));

const f0 = async () => {

await banner('W e l c o m e','  This is the Command Line Interface Guess Number Game')

await sleep();

console.log(`${chalk.bgCyanBright('\nHOW TO PLAY')} `);
console.log(`You have to guess the number generated by the computer.
If you get any two guess wrong you will be ${chalk.bgRed('killed')}
So get more than two guess's correct to become a ${chalk.bgGreenBright(`winner`)}...`);

await sleep()

}


const f1 =async () => {

 let random_number= Math.floor(Math.random() * 5);

let ans= await inquirer.prompt({
  name: 'guess_number',
  type: 'number',
  message: chalk.greenBright('Guess the number between 1-5'),
  default(){
   return 'Number' ;
  }
 })

 let spinner= createSpinner('Checking number...').start();
 await sleep();

 if(ans.guess_number == random_number ){
  spinner.success({text: chalk.cyanBright('Correct')});
 count++;
 }
 else{
  spinner.error( {text: chalk.bgRed('Wrong Guess\n') });

  count--;
 }
}


await f0();
await sleep();
do{

 let rainbow= chalkAnimation.rainbow(`\nRound ${round}:\n`);
 await sleep();
 rainbow.stop();

 await f1();
 round++;
 await sleep();

}
while(round<=5)

if(count <= 2){
figlet('💀💀💀 Game over, you Loose ',function(error,data){
 console.log(gradient.mind(data))
})
}
else{
 figlet('Congratulations! You Win.',function(error,data){
  console.log(gradient.teen(data));
  
 })
}